### ISSUE TITLE
source-map-support incompatible with tsx

### ISSUE THREAD

**Issue by schnz** [pinojs/pino-caller#144]
I am not sure where to open this issue. Ultimately it more likely belongs to either the `source-map-support` repo or the [`tsx`](https://github.com/privatenumber/tsx) repo. But I wonder if `source-map-support` needs to be a requirement at all.

**Issue at hand:**
When using `tsx` in conjunction with `pino` and `pino-caller`, the line numbers in the stack traces are getting messed up.

It is best demonstrated with a minimal example:

**Working scenario (_without_ pino-caller)**

`index.ts`
```ts
import { pino } from "pino";

const log = pino();

log.error({ err: new Error("artrifical error") }, "error");
 ```

Output (correctly reports `index.ts:5:18`)
```bash
$ npx tsx index.ts | npx pino-pretty -S
[12:37:31.996] ERROR (65194): error
    err: {
      "type": "Error",
      "message": "artrifical error",
      "stack":
          Error: artrifical error
              at <anonymous> (/data/user/Downloads/demo/index.ts:5:18)
              at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
              at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
              at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
    }
```

**Defect scenario (with pino-caller)**

`index.ts`

```ts
import { pino } from "pino";
import pinoCaller from "pino-caller";

const log = pinoCaller.default(pino());

log.error({ err: new Error("artrifical error") }, "error");
```

Output (incorrectly reports `index.ts:1:112`)
```bash
$ npx tsx index.ts | npx pino-pretty -S
[12:40:21.134] ERROR (66060) <file:///user/markus/Downloads/demo/index.ts:1:101>: error
    err: {
      "type": "Error",
      "message": "artrifical error",
      "stack":
          Error: artrifical error
              at file:///data/user/Downloads/demo/index.ts:1:112
              at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
              at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
              at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
    }
```

---

This is ultimately caused by the `require('source-map-support/register')` line in pino-caller. More specifically, it seems to be caused by the `Error.prepareStackTrace` override that happens inside `source-map-support`. I didn't dig any deeper than that. But I was wondering whether pino-caller needs this line of code in the first place:

Quote from their [README.md](https://github.com/evanw/node-source-map-support?tab=readme-ov-file#installation-and-usage):
> This package is no longer required as [Node 12.12.0 introduced the --enable-source-maps flag.](https://nodejs.org/docs/latest-v16.x/api/cli.html#--enable-source-maps)

Node v12 was released 5 years ago and its extended support ran out over 2 years ago. Given all of that, I would argue that removing `source-map-support` package is an easy fix and it is no longer needed for any sane use-case.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mahmoodhamdi** [comment]
The root cause is the hard dependency on `source-map-support` at the top of `index.js`:

```js
require("source-map-support/register")
```

This unconditionally registers `source-map-support`, which conflicts with `tsx` (which uses its own source map handling via `esbuild`). When both try to process source maps, they step on each other and produce wrong line numbers.

A few possible approaches:

1. **Make `source-map-support` optional** — only register it if no other source map handler is active:
   ```js
   try {
     if (!Error.prepareStackTrace.__sourceMapSupport) {
       require("source-map-support/register")
     }
   } catch {
     // source-map-support not installed or another handler is active
   }
   ```

2. **Remove the hard dependency entirely** — modern Node.js (v20.16+, v22.6+) has built-in source map support via `--enable-source-maps`. And tools like `tsx`, `ts-node`, `esbuild-register` all handle their own source maps. The `source-map-support` package is becoming less necessary.

3. **Add an option to disable it**:
   ```js
   function traceCaller(pinoInstance, options = {}) {
     if (options.sourceMap !== false) {
       require("source-map-support/register")
     }
     // ...
   }
   ```

Option 2 would be the cleanest for a major version bump. For a non-breaking fix, option 3 with a default of `true` (backward compatible) would work.

I'd be happy to submit a PR for this if there's a preferred approach.

**Comment by schnz** [comment]
Just FYI: #145 implements option 2

Am 15. März 2026 21:22:53 schrieb Mahmoud Hamdy ***@***.***>:
