### ISSUE TITLE
Customize caller format

### ISSUE THREAD

**Issue by thewh1teagle** [pinojs/pino-caller#147]
I use pino caller to see where errors happens easily.

```ts
/*
Set LOG_LEVEL to one of (debug, error, fatal, info, silent, trace, warn)

*/
import pino from "pino";
import pinoCaller from "pino-caller";

var log = pino({
	level: process.env.LOG_LEVEL?.toLowerCase() ?? 'info',
  transport: {
    target: "pino-pretty",
    options: {
        messageFormat: '{msg}',
        ignore: 'pid,hostname,filename',
    }
  },
});
var log = pinoCaller(log)

export default log;
```

The current output is:

```console
bun run src/index.ts
[14:31:23.288] ERROR <module code (/Volumes/Internal/pino/src/other.ts:3:4)>: other.ts
[14:31:23.297] ERROR <module code (/Volumes/Internal/pino/src/index.ts:3:4)>: index.ts
```

How can I configure it to be like:

```console
[14:31:23.288] ERROR at /Volumes/Internal/pino/src/other.ts:3:4: other.ts
[14:31:23.297] ERROR at /Volumes/Internal/pino/src/index.ts:3:4: index.ts
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mahmoodhamdi** [comment]
The format of the `caller` property comes from the raw stack trace string. Currently pino-caller just strips a fixed prefix (`substr(LINE_OFFSET)`) and optionally removes the `relativeTo` path, but there's no way to customize the format itself.

For your specific case, you can work around this by using a `mixin` function in pino instead of pino-caller:

```js
import pino from "pino"

function getCallerInfo() {
  const stack = new Error().stack.split("\n")
  const callerLine = stack.find(
    (line, i) => i > 1 && \!line.includes("node_modules/pino") && \!line.includes("node_modules\\pino")
  )
  if (\!callerLine) return ""
  const match = callerLine.match(/\((.+)\)/) || callerLine.match(/at\s+(.+)/)
  return match ? match[1].trim() : callerLine.trim()
}

const logger = pino({
  level: process.env.LOG_LEVEL?.toLowerCase() ?? "info",
  mixin() {
    return { caller: `at ${getCallerInfo()}` }
  },
  transport: {
    target: "pino-pretty",
    options: {
      messageFormat: "{msg}",
      ignore: "pid,hostname",
    },
  },
})
```

This gives you full control over the format. The output would look like:
```
[14:31:23.288] ERROR at /Volumes/Internal/pino/src/other.ts:3:4: other.ts
```

That said, a `formatCaller` option in pino-caller itself would be a nice addition — something like:

```js
const log = pinoCaller(pino(), {
  formatCaller: (raw) => `at ${raw.replace(/^.*\(/, "").replace(/\)$/, "")}`
})
```

Regarding `logger.debug("hello", "world")` — pino intentionally does not work like `console.log`. The first argument to pino methods is either a merge object or the message string:

```js
logger.debug("hello")                    // message = "hello"
logger.debug({ key: "val" }, "hello")    // merge object + message
logger.debug("hello %s", "world")        // printf-style interpolation → "hello world"
```

So `logger.debug("hello", "world")` uses printf-style — but since there's no `%s` placeholder, `"world"` is ignored. Use `logger.debug("hello %s", "world")` instead.

**Comment by mahmoodhamdi** [comment]
I've submitted a PR to add this: #180

It adds two new options:
- `formatCaller(caller)` — transform the raw caller string however you like
- `callerKey` — use a custom property name instead of `"caller"`

With these options, the example from the issue would look like:

```js
const log = pinoCaller(pino(), {
  formatCaller: (raw) => {
    const match = raw.match(/\((.+)\)/)
    return match ? "at " + match[1] : "at " + raw
  }
})
```

Output:
```
[14:31:23.288] ERROR at /Volumes/Internal/pino/src/other.ts:3:4: other.ts
```
