### ISSUE TITLE
offsets is wrong when using with pino-debug

### ISSUE THREAD

**Issue by gregory** [pinojs/pino-caller#16]
i'm using pino-debug along with pino-caller, changing the stack trace which is then printing the wrong line: 
```Error
    at eval (eval at asJson (/project/node_modules/pino-caller/index.js:16:5), <anonymous>:1:7)
    at Object.asJson (/project/node_modules/pino-caller/index.js:16:5)
    at Object.write (/project/node_modules/pino/lib/proto.js:140:28)
    at Object.LOG [as debug] (/project/node_modules/pino/lib/tools.js:37:26)
    at enabled (/project/node_modules/pino-debug/debug.js:19:16)
    at Object.<anonymous> (/project/packages/something/lib/index.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)```

will print `"Object.LOG [as debug] (/project/node_modules/pino/lib/tools.js:37:26)"`

It would be nice to be able to tweak the offsets.

**Comment by phra** [comment]
can you please check out #18 and tell if it does fix your problem?

**Comment by gregory** [comment]
> can you please check out #18 and tell if it does fix your problem?

It does not. #18 is fixing the tests though. See below how [this commit](https://github.com/pinojs/pino-caller/pull/19/commits/7c4769b3f5a4787c13817d0f5aaf2e3362180ce2) fixed the test. 
<img width="787" alt="Screen Shot 2019-11-22 at 11 00 32" src="https://user-images.githubusercontent.com/167488/69452766-559d4300-0d17-11ea-8a6e-99c95a6e21c9.png">
