### ISSUE TITLE
TypeError: Cannot assign to read only property 'asJson' of object '#<EventEmitter>'

### ISSUE THREAD

**Issue by christiansaiki** [pinojs/pino-caller#2]
I'm using this code to test pino-caller

```javascript
'use strict'
// dinamically load the plugin if in development environment
const pino =  require('pino-caller')(require('pino')())

pino.info('info1')
pino.error('error1')
pino.debug('debug1')
```

but I keep getting this errors

/Users/chris/development/pinoTest/node_modules/pino-caller/index.js:7
  return Object.assign(Object.create(pinoInstance), {
                ^

TypeError: Cannot assign to read only property 'asJson' of object '#<EventEmitter>'
    at traceCaller (/Users/chris/development/pinoTest/node_modules/pino-caller/index.js:7:17)
    at Object.<anonymous> (/Users/chris/development/pinoTest/logTest.js:3:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

Could you please help me?

**Comment by phra** [comment]
thanks for the issue. i will look into it.

**Comment by phra** [comment]
fixed. please upgrade to ^2.0.0

**Comment by christiansaiki** [comment]
Thanks :)
